spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
  datasource:
    platform: h2
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
  data:
    rest:
      enable-enum-translation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

server:
  forward-headers-strategy: native